// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthafZSP-tFkdM9FPeXBO-Fn3wZqq69TY',
    appId: '1:908780155139:web:92ab753ef90e90f7aef936',
    messagingSenderId: '908780155139',
    projectId: 'tbasvregenstauf-f5ae6',
    authDomain: 'tbasvregenstauf-f5ae6.firebaseapp.com',
    databaseURL: 'https://tbasvregenstauf-f5ae6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tbasvregenstauf-f5ae6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoldlvaP51YxWeMvGIarj2D_PS9QHrD6E',
    appId: '1:908780155139:android:39afefdf94a3345eaef936',
    messagingSenderId: '908780155139',
    projectId: 'tbasvregenstauf-f5ae6',
    databaseURL: 'https://tbasvregenstauf-f5ae6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tbasvregenstauf-f5ae6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQUi5kBbu4qjFZ7el9GZgmXBAHMPLieNI',
    appId: '1:908780155139:ios:ba2bfb9a2dffec7eaef936',
    messagingSenderId: '908780155139',
    projectId: 'tbasvregenstauf-f5ae6',
    databaseURL: 'https://tbasvregenstauf-f5ae6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tbasvregenstauf-f5ae6.appspot.com',
    iosBundleId: 'com.example.tennisClubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQUi5kBbu4qjFZ7el9GZgmXBAHMPLieNI',
    appId: '1:908780155139:ios:a4d2e719f1669b9aaef936',
    messagingSenderId: '908780155139',
    projectId: 'tbasvregenstauf-f5ae6',
    databaseURL: 'https://tbasvregenstauf-f5ae6-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tbasvregenstauf-f5ae6.appspot.com',
    iosBundleId: 'com.example.tennisClubApp.RunnerTests',
  );
}
